version: '3.8'

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DATABASE: wine_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    image: postgres:11.6
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres
      - ./scripts:/docker-entrypoint-initdb.d

  wineapp:
    container_name: wineapp
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRINGDOC_SWAGGER_UI_PATH: /swagger
    expose:
      - 8080
    image: mikaalaoutinen/wineapp:latest
    ports:
      - 8082:8080
    restart: unless-stopped

volumes:
  pg_data: