version: '3'

services:
  # Backend API
  wineapp:
    build: .
    container_name: wineapp
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin     
      SPRINGDOC_SWAGGER_UI_PATH: /swagger
    expose:
      - 8080
    image: wineapp
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
    restart: unless-stopped
  
  # Database
  postgres:
    container_name: postgres
    environment:
      # POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      # MYSQL_USER: ${POSTGRES_USER}
      # MYSQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: wine_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    image: postgres:11.6
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres

networks:
  backend:
  frontend:
    
volumes:
  pg_data: