############################
# Config for running tests #
############################

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tesdb
    username: sa
    password:

# Allow connections from this URL:
frontend:
  url: http://localhost:8081