server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Is user authentication and authorization required
  security:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger