server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update

  # Is user authentication and authorization required
  security:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  expiration: 900000 # Expiration time is 15 min
  secret: jwt_secret