server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wine_app
    username: admin
    password: admin
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

  # Is user authentication and authorization required
  security:
    enabled: true

jwt:
  expiration: 18000000 # Expiration time is 30 min
  secret: jwt_secret

# Used in LoadDatabase to create an initial admin user
admin:
  username: admin
  password: password

# Allow connections from these URLs:
frontend:
  urls: http://localhost:8081,http://localhost:3000


# Wine parser settings:

# If set to true, TextParser will ping the url to see if it is still valid.
# This should be set to false by default.
parser:
  validate-url: false