server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update

  # Is user authentication and authorization required
  security:
    enabled: true

# localhost:8080/api/swagger
springdoc:
  swagger-ui:
    path: /swagger

jwt:
  expiration: 900000 # Expiration time is 15 min
  secret: jwt_secret

# Used in LoadDatabase to create an initial admin user
admin:
  username: admin
  password: password

# Allow connections from this URL:
frontend:
  url: http://localhost:8081