developerName: Mika Alaoutinen

# packages
basePackage: openapi
apiPackage: api
modelPackage: model

# Java settings
booleanGetterPrefix: is
dateLibrary: java8
performBeanValidation: false
useOptional: true

# code generation settings
implicitHeaders: true
interfaceOnly: true
openApiNullable: false
modelNameSuffix: DTO
skipDefaultInterface: true
sourceFolder: openapi
