developerName: Mika Alaoutinen

# The api and model packages have to be prefixed with com.mika or the build breaks.
apiPackage: com.mika.api
modelPackage: com.mika.model
sourcePackage: src

# Java settings
booleanGetterPrefix: is
dateLibrary: java8
performBeanValidation: true

# code generation settings
implicitHeaders: true
interfaceOnly: true
modelNameSuffix: DTO
openApiNullable: false
skipDefaultInterface: true
useTags: true

# Needed to make MapStruct work with OpenAPI generator
additionalModelTypeAnnotations: "@lombok.NoArgsConstructor @lombok.AllArgsConstructor"
