developerName: Mika Alaoutinen

# packages
basePackage: openapi
apiPackage: api
modelPackage: model
sourceFolder: src

# Java settings
booleanGetterPrefix: is
dateLibrary: java8
performBeanValidation: false

# code generation settings
implicitHeaders: true
interfaceOnly: true
modelNameSuffix: DTO
openApiNullable: false
skipDefaultInterface: true
useTags: true

additionalModelTypeAnnotations: "@lombok.NoArgsConstructor @lombok.AllArgsConstructor"