developerName: Mika Alaoutinen

# packages
basePackage: openapi
apiPackage: api
modelPackage: model
sourceFolder: src

# Java settings
booleanGetterPrefix: is
dateLibrary: java8
performBeanValidation: false

# code generation settings
implicitHeaders: true
interfaceOnly: true
modelNameSuffix: DTO
openApiNullable: false
skipDefaultInterface: true
useTags: true

# At least some of these are needed to get MapStruct working with the OpenAPI generated classes.
# Without these, the Entity -> DTO mapping fails because the DTO classes do not have normal setters.
additionalModelTypeAnnotations:
  - @lombok.Builder
  - @lombok.NoArgsConstructor
  - @lombok.AllArgsConstructor