# Workflow for development branches.
# Compiles the code and runs tests on push.

name: Development branch

on:
  push:
    branches-ignore:
      - master
      - release*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Build and test with Maven
        run: mvn -B clean package --file pom.xml
