# Workflow for master branch.
# Compiles the code, runs tests and creates a new Maven release on push.

name: Master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Build and test with Maven
        run: mvn -B clean package --file pom.xml

  release:
    name: Creates new Maven release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
        release-branch-name: master
        git-release-bot-name: release-bot
        git-release-bot-email: release-bot@example.com
        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        maven-args: -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip