# Workflow for master branch.
#
# Executes the following jobs:
#   1) Compile and test the code.
#   2) Add a new Git tag.
#   3) Builds and publishes a Docker image of the new version.

name: Master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Build and test with Maven
        run: mvn -B clean package --file pom.xml

  tag:
    name: Bump version and add tag
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  docker:
    name: Creates Docker image and pushes it to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mikaalaoutinen/wineapp
          tags: latest