# Workflow for master branch.
# Compiles the code, runs tests, bumps up version and adds new tag.

name: Master branch

on:
  push:
    branches:
      - master
      - actions

jobs:
#  build:
#    name: Build and run tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 13
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.13
#      - name: Build and test with Maven
#        run: mvn -B clean package --file pom.xml

  release:
    name: Bump version and add tag
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true